### ISSUE TITLE
Forcing matplotlib backend causing warnings on MacOSX

### ISSUE THREAD

**Issue by danielbdias** [pyrddlgym-project/pyRDDLGym-jax#3]
Depending on the python installation on MacOSX, mathplotlib uses a native backend instead of `tk`.

Is there a way to allow the user to define their own backend? Or is it necessary to use `TkAgg` as a backend?

This is causing JaxPlan to emit a confusing warning like this one:
```
Traceback (most recent call last):
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/pyRDDLGym_jax/core/planner.py", line 40, in <module>
    matplotlib.use('TkAgg')
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/matplotlib/__init__.py", line 1255, in use
    plt.switch_backend(name)
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
    module = backend_registry.load_backend_module(newbackend)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbdias/.asdf/installs/python/3.12.4/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/Users/danielbdias/Development/Repositories/doctorate/ptb-abstraction-experimentation/_venv/lib/python3.12/site-packages/matplotlib/backends/_backend_tk.py", line 9, in <module>
    import tkinter as tk
  File "/Users/danielbdias/.asdf/installs/python/3.12.4/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by mike-gimelfarb** [comment]
Thanks, this has been fixed.
